blacklisted:
  - id: '1227802414086619219'
    reason: Ninjalooting in raid - Exaton
  - id: '618324359102332929'
    reason: Ninjalooting
  - id: '793965220254580757'
    reason: Flaiming on normal mechanics and be mean to ppl.
settings:
  - guild: '1121534671667339324'
    welcomeMessage: true
    CharNameAsk: true
    BlockList: true
    welcomeChannel: '1242902565520146552'
    guildName: RSA Legends
  - guild: '1254444159985651712'
    welcomeMessage: true
    welcomeChannel: '1257409141694005368'
    CharNameAsk: false
    BlockList: true
    guildName: Warmane Tool
  - guild: '298051398103334912'
    welcomeMessage: false
    welcomeChannel: ''
    CharNameAsk: true
    BlockList: true
    guildName: The Exalted Pugs
