blacklisted:
  - id: '1227802414086619219'
    reason: Ninjalooting in raid - Exaton
  - id: '618324359102332929'
    reason: Ninjalooting
  - id: '744124194647703604'
    reason: 'Reason: Inappropriate behavior in global chat. Racism'
settings:
  - guild: '1121534671667339324'
    welcomeMessage: true
    CharNameAsk: true
    BlockList: true
    welcomeChannel: '1242902565520146552'
    guildName: RSA Legends
    charNameAskDM: >-
      Hey, I would like to ask you for your main Character name.

      Please respond with your main Character name for the Server.


      (Your response will not be stored by this Application and is only used for
      the Guilds nickname)
    lastOwnerDM: {}
    language: en
  - guild: '1254444159985651712'
    welcomeMessage: true
    welcomeChannel: '1257409141694005368'
    CharNameAsk: true
    BlockList: true
    guildName: Warmane Tool
    charNameAskDM: |-
      Hey, we kindly want to ask you how we should name you :)

      Please Respond with the name you want to be called.
      The Response will not be stored on the database!
    lastOwnerDM: {}
    language: en
  - guild: '298051398103334912'
    welcomeMessage: false
    welcomeChannel: ''
    CharNameAsk: true
    BlockList: true
    guildName: The Exalted Pugs
    charNameAskDM: >-
      Hey, I would like to ask you for your main Character name.

      Please respond with your main Character name for the Server.


      (Your response will not be stored by this Application and is only used for
      the Guilds nickname)
    lastOwnerDM: {}
    language: en
  - guild: '512184428148031488'
    guildName: KAMIKAZZI
    welcomeMessage: false
    welcomeChannel: ''
    CharNameAsk: false
    BlockList: true
    charNameAskDM: >-
      Hey, I would like to ask you for your main Character name.

      Please respond with your main Character name for the Server.


      (Your response will not be stored by this Application and is only used for
      the Guilds nickname)
    lastOwnerDM: {}
    language: en
  - guild: '591867643066056704'
    guildName: The Flat Azeroth Society
    welcomeMessage: false
    welcomeChannel: ''
    CharNameAsk: true
    BlockList: true
    charNameAskDM: >-
      Hey, I would like to ask you for your main Character name.

      Please respond with your main Character name for the Server.


      (Your response will not be stored by this Application and is only used for
      the Guilds nickname)
    lastOwnerDM:
      '432161293227524116': 1736322239606
    language: en
  - guild: '605146558777917461'
    guildName: zzz
    welcomeMessage: false
    welcomeChannel: ''
    CharNameAsk: false
    BlockList: true
    charNameAskDM: >-
      Hey, I would like to ask you for your main Character name.

      Please respond with your main Character name for the Server.


      (Your response will not be stored by this Application and is only used for
      the Guilds nickname)
    lastOwnerDM: {}
    language: en
  - guild: '675405604436705281'
    guildName: S Ꮒ Ꭷ ฬ T Ꭵ Ꮇ Ꮛ S
    welcomeMessage: false
    welcomeChannel: ''
    CharNameAsk: false
    BlockList: true
    charNameAskDM: >-
      Hey, I would like to ask you for your main Character name.

      Please respond with your main Character name for the Server.


      (Your response will not be stored by this Application and is only used for
      the Guilds nickname)
    lastOwnerDM: {}
    language: en
  - guild: '907417335223181342'
    guildName: 4uk's server
    welcomeMessage: false
    welcomeChannel: ''
    CharNameAsk: false
    BlockList: true
    charNameAskDM: >-
      Hey, I would like to ask you for your main Character name.

      Please respond with your main Character name for the Server.


      (Your response will not be stored by this Application and is only used for
      the Guilds nickname)
    lastOwnerDM: {}
    language: en
  - guild: '961639048248692747'
    guildName: The Window Lickers
    welcomeMessage: false
    welcomeChannel: ''
    CharNameAsk: false
    BlockList: true
    charNameAskDM: >-
      Hey, I would like to ask you for your main Character name.

      Please respond with your main Character name for the Server.


      (Your response will not be stored by this Application and is only used for
      the Guilds nickname)
    lastOwnerDM: {}
    language: en
  - guild: '983787277341823016'
    guildName: Divine Dragons
    welcomeMessage: false
    welcomeChannel: ''
    CharNameAsk: false
    BlockList: true
    charNameAskDM: >-
      Hey, I would like to ask you for your main Character name.

      Please respond with your main Character name for the Server.


      (Your response will not be stored by this Application and is only used for
      the Guilds nickname)
    lastOwnerDM: {}
    language: en
  - guild: '1026098702500249653'
    guildName: Ardenweald
    welcomeMessage: false
    welcomeChannel: ''
    CharNameAsk: false
    BlockList: true
    charNameAskDM: >-
      Hey, I would like to ask you for your main Character name.

      Please respond with your main Character name for the Server.


      (Your response will not be stored by this Application and is only used for
      the Guilds nickname)
    lastOwnerDM: {}
    language: en
  - guild: '1065996759932878959'
    guildName: High Table!
    welcomeMessage: false
    welcomeChannel: ''
    CharNameAsk: false
    BlockList: true
    charNameAskDM: >-
      Hey, I would like to ask you for your main Character name.

      Please respond with your main Character name for the Server.


      (Your response will not be stored by this Application and is only used for
      the Guilds nickname)
    lastOwnerDM: {}
    language: en
  - guild: '1201497400083226726'
    guildName: Lights Vengeance
    welcomeMessage: false
    welcomeChannel: ''
    CharNameAsk: false
    BlockList: true
    charNameAskDM: >-
      Hey, I would like to ask you for your main Character name.

      Please respond with your main Character name for the Server.


      (Your response will not be stored by this Application and is only used for
      the Guilds nickname)
    lastOwnerDM: {}
    language: en
  - guild: '1290529693665202208'
    guildName: TRES IDIOTAS
    welcomeMessage: false
    welcomeChannel: ''
    CharNameAsk: false
    BlockList: true
    charNameAskDM: >-
      Hey, I would like to ask you for your main Character name.

      Please respond with your main Character name for the Server.


      (Your response will not be stored by this Application and is only used for
      the Guilds nickname)
    lastOwnerDM:
      '299209989174722560': 1736185303422
    language: en
  - guild: '1330716535614079099'
    guildName: My Manas Low BRB
    welcomeMessage: false
    welcomeChannel: '1330716536050028607'
    CharNameAsk: true
    BlockList: true
    charNameAskDM: >-
      Hey, I would like to ask you for your main Character name.

      Please respond with your main Character name for the Server.


      (Your response will not be stored by this Application and is only used for
      the Guilds nickname)
    lastOwnerDM: {}
    language: en
  - guild: '1203421848663097414'
    guildName: test
    welcomeMessage: false
    welcomeChannel: ''
    CharNameAsk: false
    BlockList: true
    charNameAskDM: >-
      Hey, I would like to ask you for your main Character name.

      Please respond with your main Character name for the Server.


      (Your response will not be stored by this Application and is only used for
      the Guilds nickname)
    lastOwnerDM: {}
    language: en
  - guild: '1325151914827976794'
    guildName: Caverna
    welcomeMessage: false
    welcomeChannel: ''
    CharNameAsk: false
    BlockList: true
    language: en
    charNameAskDM: >-
      Hey, I would like to ask you for your main Character name.

      Please respond with your main Character name for the Server.


      (Your response will not be stored by this Application and is only used for
      the Guilds nickname)
    lastOwnerDM: {}
  - guild: '1171820013339025500'
    guildName: Test
    welcomeMessage: true
    welcomeChannel: ''
    CharNameAsk: false
    BlockList: true
    language: en
    charNameAskDM: >-
      Hey, I would like to ask you for your main Character name.

      Please respond with your main Character name for the Server.


      (Your response will not be stored by this Application and is only used for
      the Guilds nickname)
    lastOwnerDM: {}
  - guild: '542696785202774027'
    guildName: Old Division
    welcomeMessage: false
    welcomeChannel: ''
    CharNameAsk: false
    BlockList: true
    language: en
    charNameAskDM: >-
      Hey, I would like to ask you for your main Character name.

      Please respond with your main Character name for the Server.


      (Your response will not be stored by this Application and is only used for
      the Guilds nickname)
    lastOwnerDM: {}
  - guild: '254185687643979786'
    guildName: Jezu Kurna
    welcomeMessage: false
    welcomeChannel: ''
    CharNameAsk: false
    BlockList: true
    language: en
    charNameAskDM: >-
      Hey, I would like to ask you for your main Character name.

      Please respond with your main Character name for the Server.


      (Your response will not be stored by this Application and is only used for
      the Guilds nickname)
    lastOwnerDM: {}
  - guild: '1331270035825754123'
    guildName: Warmane Onyxia Asia
    welcomeMessage: false
    welcomeChannel: ''
    CharNameAsk: false
    BlockList: true
    language: en
    charNameAskDM: >-
      Hey, I would like to ask you for your main Character name.

      Please respond with your main Character name for the Server.


      (Your response will not be stored by this Application and is only used for
      the Guilds nickname)
    lastOwnerDM: {}
userCharacters:
  '209319089930240004':
    alts:
      - name: Zalacar
        realm: Icecrown
        addedBy: '209319089930240004'
        addedAt: '2025-01-27T13:03:29.431Z'
      - name: Ravaged
        realm: Icecrown
        addedBy: '209319089930240004'
        addedAt: '2025-01-27T13:13:19.887Z'
      - name: Zeralock
        realm: Icecrown
        addedBy: '209319089930240004'
        addedAt: '2025-01-27T13:13:41.379Z'
      - name: Branched
        realm: Icecrown
        addedBy: '209319089930240004'
        addedAt: '2025-01-27T13:14:00.745Z'
      - name: Honestly
        realm: Icecrown
        addedBy: '209319089930240004'
        addedAt: '2025-01-27T13:14:28.059Z'
      - name: Insaneuh
        realm: Icecrown
        addedBy: '209319089930240004'
        addedAt: '2025-01-27T13:14:44.678Z'
      - name: Insanepq
        realm: Icecrown
        addedBy: '209319089930240004'
        addedAt: '2025-01-27T13:17:45.584Z'
    main:
      name: Mirafirst
      realm: Icecrown
      addedBy: '209319089930240004'
      addedAt: '2025-01-27T13:03:07.997Z'
