blacklisted:
  - id: '1227802414086619219'
    reason: Ninjalooting in raid - Exaton
  - id: '618324359102332929'
    reason: Ninjalooting
settings:
  - guild: '1121534671667339324'
    welcomeMessage: true
    CharNameAsk: true
    BlockList: true
    welcomeChannel: '1242902565520146552'
    guildName: RSA Legends
    charNameAskDM: >-
      Hey, I would like to ask you for your main Character name.

      Please respond with your main Character name for the Server.


      (Your response will not be stored by this Application and is only used for
      the Guilds nickname)
    lastOwnerDM: {}
  - guild: '1254444159985651712'
    welcomeMessage: true
    welcomeChannel: '1257409141694005368'
    CharNameAsk: false
    BlockList: true
    guildName: Warmane Tool
    charNameAskDM: >-
      Hey, I would like to ask you for your main Character name.

      Please respond with your main Character name for the Server.


      (Your response will not be stored by this Application and is only used for
      the Guilds nickname)
    lastOwnerDM: {}
  - guild: '298051398103334912'
    welcomeMessage: false
    welcomeChannel: ''
    CharNameAsk: true
    BlockList: true
    guildName: The Exalted Pugs
    charNameAskDM: >-
      Hey, I would like to ask you for your main Character name.

      Please respond with your main Character name for the Server.


      (Your response will not be stored by this Application and is only used for
      the Guilds nickname)
    lastOwnerDM: {}
  - guild: '512184428148031488'
    guildName: KAMIKAZZI
    welcomeMessage: false
    welcomeChannel: ''
    CharNameAsk: false
    BlockList: true
    charNameAskDM: >-
      Hey, I would like to ask you for your main Character name.

      Please respond with your main Character name for the Server.


      (Your response will not be stored by this Application and is only used for
      the Guilds nickname)
    lastOwnerDM: {}
  - guild: '591867643066056704'
    guildName: The Flat Azeroth Society
    welcomeMessage: false
    welcomeChannel: ''
    CharNameAsk: true
    BlockList: true
    charNameAskDM: >-
      Hey, I would like to ask you for your main Character name.

      Please respond with your main Character name for the Server.


      (Your response will not be stored by this Application and is only used for
      the Guilds nickname)
    lastOwnerDM: {}
  - guild: '605146558777917461'
    guildName: zzz
    welcomeMessage: false
    welcomeChannel: ''
    CharNameAsk: false
    BlockList: true
    charNameAskDM: >-
      Hey, I would like to ask you for your main Character name.

      Please respond with your main Character name for the Server.


      (Your response will not be stored by this Application and is only used for
      the Guilds nickname)
    lastOwnerDM: {}
  - guild: '675405604436705281'
    guildName: S Ꮒ Ꭷ ฬ T Ꭵ Ꮇ Ꮛ S
    welcomeMessage: false
    welcomeChannel: ''
    CharNameAsk: false
    BlockList: true
    charNameAskDM: >-
      Hey, I would like to ask you for your main Character name.

      Please respond with your main Character name for the Server.


      (Your response will not be stored by this Application and is only used for
      the Guilds nickname)
    lastOwnerDM: {}
  - guild: '888208015050821642'
    guildName: test1
    welcomeMessage: false
    welcomeChannel: ''
    CharNameAsk: false
    BlockList: true
    charNameAskDM: >-
      Hey, I would like to ask you for your main Character name.

      Please respond with your main Character name for the Server.


      (Your response will not be stored by this Application and is only used for
      the Guilds nickname)
    lastOwnerDM: {}
  - guild: '907417335223181342'
    guildName: 4uk's server
    welcomeMessage: false
    welcomeChannel: ''
    CharNameAsk: false
    BlockList: true
    charNameAskDM: >-
      Hey, I would like to ask you for your main Character name.

      Please respond with your main Character name for the Server.


      (Your response will not be stored by this Application and is only used for
      the Guilds nickname)
    lastOwnerDM: {}
  - guild: '961639048248692747'
    guildName: The Window Lickers
    welcomeMessage: false
    welcomeChannel: ''
    CharNameAsk: false
    BlockList: true
    charNameAskDM: >-
      Hey, I would like to ask you for your main Character name.

      Please respond with your main Character name for the Server.


      (Your response will not be stored by this Application and is only used for
      the Guilds nickname)
    lastOwnerDM: {}
  - guild: '983787277341823016'
    guildName: Divine Dragons
    welcomeMessage: false
    welcomeChannel: ''
    CharNameAsk: false
    BlockList: true
    charNameAskDM: >-
      Hey, I would like to ask you for your main Character name.

      Please respond with your main Character name for the Server.


      (Your response will not be stored by this Application and is only used for
      the Guilds nickname)
    lastOwnerDM: {}
  - guild: '1026098702500249653'
    guildName: Ardenweald
    welcomeMessage: false
    welcomeChannel: ''
    CharNameAsk: false
    BlockList: true
    charNameAskDM: >-
      Hey, I would like to ask you for your main Character name.

      Please respond with your main Character name for the Server.


      (Your response will not be stored by this Application and is only used for
      the Guilds nickname)
    lastOwnerDM: {}
  - guild: '1065996759932878959'
    guildName: High Table!
    welcomeMessage: false
    welcomeChannel: ''
    CharNameAsk: false
    BlockList: true
    charNameAskDM: >-
      Hey, I would like to ask you for your main Character name.

      Please respond with your main Character name for the Server.


      (Your response will not be stored by this Application and is only used for
      the Guilds nickname)
    lastOwnerDM: {}
  - guild: '1201497400083226726'
    guildName: Lights Vengeance
    welcomeMessage: false
    welcomeChannel: ''
    CharNameAsk: false
    BlockList: true
    charNameAskDM: >-
      Hey, I would like to ask you for your main Character name.

      Please respond with your main Character name for the Server.


      (Your response will not be stored by this Application and is only used for
      the Guilds nickname)
    lastOwnerDM: {}
  - guild: '1269521061532270633'
    guildName: El Den't
    welcomeMessage: false
    welcomeChannel: ''
    CharNameAsk: false
    BlockList: true
    charNameAskDM: >-
      Hey, I would like to ask you for your main Character name.

      Please respond with your main Character name for the Server.


      (Your response will not be stored by this Application and is only used for
      the Guilds nickname)
    lastOwnerDM:
      '487773810616172547': 1736189351442
  - guild: '1290529693665202208'
    guildName: TRES IDIOTAS
    welcomeMessage: false
    welcomeChannel: ''
    CharNameAsk: false
    BlockList: true
    charNameAskDM: >-
      Hey, I would like to ask you for your main Character name.

      Please respond with your main Character name for the Server.


      (Your response will not be stored by this Application and is only used for
      the Guilds nickname)
    lastOwnerDM:
      '299209989174722560': 1736185303422
  - guild: '471186202150699013'
    guildName: ArmYt's server
    welcomeMessage: false
    welcomeChannel: ''
    CharNameAsk: false
    BlockList: true
    charNameAskDM: >-
      Hey, I would like to ask you for your main Character name.

      Please respond with your main Character name for the Server.


      (Your response will not be stored by this Application and is only used for
      the Guilds nickname)
    lastOwnerDM: {}
  - guild: '1325935461436489900'
    welcomeMessage: false
    welcomeChannel: '1325935461960646758'
    CharNameAsk: false
    BlockList: true
    charNameAskDM: >-
      Hey, I would like to ask you for your main Character name.

      Please respond with your main Character name for the Server.


      (Your response will not be stored by this Application and is only used for
      the Guilds nickname)
    lastOwnerDM: {}
