name: "tagged-release"

on:
  push:
    branches:
      - "master"

permissions:
  contents: write
  packages: write

jobs:
  gh_tagged_release:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v3"
        with:
          fetch-depth: 0

      - name: "🔧 setup node"
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version: 20
          cache-dependency-path: "package-lock.json"

      - run: "npm ci"
      - run: "npm test"

      - name: "Build Changelog"
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          configuration: ".github/config/configuration.json"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.github_release.outputs.changelog }}
          prerelease: ${{ contains(github.ref, '-rc') || contains(github.ref, '-b') || contains(github.ref, '-a') }}
          files: |
            LICENSE
