name: "tagged-release"

on:
  push:
    tags:
      - "*"

permissions:
  contents: write
  packages: write

jobs:
  gh_tagged_release:
    runs-on: "ubuntu-latest"

    steps:
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          mode: "COMMIT"
          configuration: ".github/config/configuration.json"
          token: ${{ secrets.PAT }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.github_release.outputs.changelog }}
          prerelease: ${{ contains(github.ref, '-rc') || contains(github.ref, '-b') || contains(github.ref, '-a') }}
          files: |
            LICENSE