name: "tagged-release"

on:
  push:
    branches:
      - master
    tags:
      - "v*"

permissions:
  contents: write
  packages: write

jobs:
  gh_tagged_release:
    runs-on: "ubuntu-latest"

    steps:
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          mode: "HYBRID"
          configuration: ".github/config/configuration.json"
          token: ${{ secrets.PAT }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.github_release.outputs.changelog }}
          prerelease: ${{ contains(github.ref, '-rc') || contains(github.ref, '-b') || contains(github.ref, '-a') }}
          files: |
            LICENSE

      - name: Sending message
        uses: svenbledt/discord-styled-releases@main
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
