name: "tagged-release"

on:
  push:
    tags:
      - '*'

permissions:
  contents: write
  packages: write

jobs:
  gh_tagged_release:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4
        
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v5.1.0
        with:
          configuration: ".github/config/changelog.json"
          ignorePreReleases: true
          mode: "COMMIT"
          token: ${{ secrets.PAT }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.github_release.outputs.changelog }}
          draft: false
          prerelease: ${{ contains(github.ref, '-rc') || contains(github.ref, '-b') || contains(github.ref, '-a') }}
          files: |
            LICENSE.txt

  discord_notification:
    needs: gh_tagged_release
    runs-on: "ubuntu-latest"
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4
      
      - name: Get current release
        id: get_release
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/{owner}/{repo}/releases/tags/${{ github.ref_name }}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send message to discord
        uses: svenbledt/discord-styled-releases@main
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          mention_everyone: 'true'
        env:
          GITHUB_CONTEXT: ${{ steps.get_release.outputs.data }}
